name: dsacstar
channels:
    - pytorch
    - defaults
dependencies:
    - python=3.7.10 
    - cudatoolkit=10.2.89
    - pytorch=1.6.0
    - opencv=3.4.2
    - torchvision=0.7.0
    - scikit-image=0.16.2
    - pyyaml=5.3.1
